name = "landing-taptik-ai"
compatibility_date = "2024-01-15"

# Static Assets configuration
[assets]
directory = "./out"

# 환경 변수
[vars]
PNPM_VERSION = "10.8.0"
NODE_VERSION = "22"

# Build command for Cloudflare Pages
[build]
command = "pnpm install && pnpm build"
